### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by shinylyni** [SchoolIdolTomodachi/BanGDream#5]
On the create an account page, and entering your birthdate in your profile, the incorrect format 'mm-dd-yyyy' is shown and should be 'mm/dd/yyyy' instead.

**Comment by shinylyni** [comment]
According to Cara: "The issue is date fields are region specific and the prompt will be wrong if you're not in the same region as whoever made the prompt"

https://cdn.discordapp.com/attachments/295364444320694283/301484445666508800/unknown.png

**Comment by shinylyni** [comment]
The version of Chrome I'm using doesn't seem to have this issue ( 57.0.2987.133 )
However, firefox 46.0.1 does
Even thought Chrome doesn't seem to have it as an issue, the date still shows up at mm/dd/yyyy when I've selected the date I want

**Comment by db0company** [comment]
https://github.com/SchoolIdolTomodachi/MagiCircles/commit/8fb15118c89e6cd570a357b9a3d06bfb68a77413
